const calendarActionTypes = {
  GET_CALENDAR_STATUS_DATA: "GET_CALENDAR_STATUS_DATA",
  GET_CALENDAR_VALUES_DATA: "GET_CALENDAR_VALUES_DATA",
  SET_CALENDAR_CHOSEN_YEAR: "SET_CALENDAR_CHOSEN_YEAR",
  SET_CALENDAR_CHOSEN_DAY: "SET_CALENDAR_CHOSEN_DAY"
};

export default calendarActionTypes;
