 version: 2
 jobs:
   build:
     docker:
       - image: circleci/ruby:2.6.5-node-browsers
         environment:
            BUNDLER_VERSION: 2.0.2
            PGHOST: localhost
            PGUSER: root
            RAILS_ENV: test
       - image: circleci/postgres:11.5
         environment:
            POSTGRES_DB: smogalert_test
            POSTGRES_PASSWORD: ""
            POSTGRES_USER: root
     steps:
       - checkout
       # Download and cache dependencies
       - restore_cache:
           keys:
             - v1-dependencies-{{ checksum "Gemfile.lock" }}
             # fallback to using the latest cache if no exact match is found
             - v1-dependencies-

       - run:
           name: install dependencies
           command: |
             bundle install --jobs=4 --retry=3 --path vendor/bundle

       - save_cache:
           paths:
             - ./vendor/bundle
           key: v1-dependencies-{{ checksum "Gemfile.lock" }}
