const chartsActionTypes = {
  SET_CHART_CHOSEN_CITY: "SET_CHART_CHOSEN_CITY",
  SET_CHART_CHOSEN_INDICATOR: "SET_CHART_CHOSEN_INDICATOR",
  SET_CHART_CHOSEN_MONTH: "SET_CHART_CHOSEN_MONTH"
};

export default chartsActionTypes;
